export default {
  avatar: require('../assets/7.png'),
  notification: require('../assets/10.png'),
  brand: require('../assets/12.png'),
  back: require('../assets/13.png'),
  person: require('../assets/Person.png'),
  bookmark: require('../assets/Bookmark.png'),
  bookmark2: require('../assets/Bookmark2.png'),
  call: require('../assets/Call.png'),
  share: require('../assets/Share.png'),
  rate: require('../assets/Star.png'),
  logout: require('../assets/logout.png'),
  cart: require('../assets/9.png'),
  call2: require('../assets/call2.png'),
};
